/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSearchRouteImport } from './routes/_app.search'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppOwnerRouteImport } from './routes/_app.owner'
import { Route as AppMapRouteImport } from './routes/_app.map'
import { Route as AppHomeRouteImport } from './routes/_app.home'
import { Route as AppAdminRouteImport } from './routes/_app.admin'
import { Route as AppSnackbarIdRouteImport } from './routes/_app.snackbar.$id'
import { Route as AppOwnerReviewsRouteImport } from './routes/_app.owner.reviews'
import { Route as AppOwnerProfileRouteImport } from './routes/_app.owner.profile'
import { Route as AppOwnerOrdersRouteImport } from './routes/_app.owner.orders'
import { Route as AppOwnerMenuRouteImport } from './routes/_app.owner.menu'

const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSearchRoute = AppSearchRouteImport.update({
  id: '/search',
  path: '/search',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerRoute = AppOwnerRouteImport.update({
  id: '/owner',
  path: '/owner',
  getParentRoute: () => AppRoute,
} as any)
const AppMapRoute = AppMapRouteImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => AppRoute,
} as any)
const AppHomeRoute = AppHomeRouteImport.update({
  id: '/home',
  path: '/home',
  getParentRoute: () => AppRoute,
} as any)
const AppAdminRoute = AppAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AppRoute,
} as any)
const AppSnackbarIdRoute = AppSnackbarIdRouteImport.update({
  id: '/snackbar/$id',
  path: '/snackbar/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOwnerReviewsRoute = AppOwnerReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => AppOwnerRoute,
} as any)
const AppOwnerProfileRoute = AppOwnerProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppOwnerRoute,
} as any)
const AppOwnerOrdersRoute = AppOwnerOrdersRouteImport.update({
  id: '/orders',
  path: '/orders',
  getParentRoute: () => AppOwnerRoute,
} as any)
const AppOwnerMenuRoute = AppOwnerMenuRouteImport.update({
  id: '/menu',
  path: '/menu',
  getParentRoute: () => AppOwnerRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/owner': typeof AppOwnerRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/owner/menu': typeof AppOwnerMenuRoute
  '/owner/orders': typeof AppOwnerOrdersRoute
  '/owner/profile': typeof AppOwnerProfileRoute
  '/owner/reviews': typeof AppOwnerReviewsRoute
  '/snackbar/$id': typeof AppSnackbarIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/admin': typeof AppAdminRoute
  '/home': typeof AppHomeRoute
  '/map': typeof AppMapRoute
  '/owner': typeof AppOwnerRouteWithChildren
  '/profile': typeof AppProfileRoute
  '/search': typeof AppSearchRoute
  '/owner/menu': typeof AppOwnerMenuRoute
  '/owner/orders': typeof AppOwnerOrdersRoute
  '/owner/profile': typeof AppOwnerProfileRoute
  '/owner/reviews': typeof AppOwnerReviewsRoute
  '/snackbar/$id': typeof AppSnackbarIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/_app/admin': typeof AppAdminRoute
  '/_app/home': typeof AppHomeRoute
  '/_app/map': typeof AppMapRoute
  '/_app/owner': typeof AppOwnerRouteWithChildren
  '/_app/profile': typeof AppProfileRoute
  '/_app/search': typeof AppSearchRoute
  '/_app/owner/menu': typeof AppOwnerMenuRoute
  '/_app/owner/orders': typeof AppOwnerOrdersRoute
  '/_app/owner/profile': typeof AppOwnerProfileRoute
  '/_app/owner/reviews': typeof AppOwnerReviewsRoute
  '/_app/snackbar/$id': typeof AppSnackbarIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/home'
    | '/map'
    | '/owner'
    | '/profile'
    | '/search'
    | '/owner/menu'
    | '/owner/orders'
    | '/owner/profile'
    | '/owner/reviews'
    | '/snackbar/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/reset-password'
    | '/admin'
    | '/home'
    | '/map'
    | '/owner'
    | '/profile'
    | '/search'
    | '/owner/menu'
    | '/owner/orders'
    | '/owner/profile'
    | '/owner/reviews'
    | '/snackbar/$id'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/forgot-password'
    | '/reset-password'
    | '/_app/admin'
    | '/_app/home'
    | '/_app/map'
    | '/_app/owner'
    | '/_app/profile'
    | '/_app/search'
    | '/_app/owner/menu'
    | '/_app/owner/orders'
    | '/_app/owner/profile'
    | '/_app/owner/reviews'
    | '/_app/snackbar/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/search': {
      id: '/_app/search'
      path: '/search'
      fullPath: '/search'
      preLoaderRoute: typeof AppSearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner': {
      id: '/_app/owner'
      path: '/owner'
      fullPath: '/owner'
      preLoaderRoute: typeof AppOwnerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/map': {
      id: '/_app/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof AppMapRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/home': {
      id: '/_app/home'
      path: '/home'
      fullPath: '/home'
      preLoaderRoute: typeof AppHomeRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/admin': {
      id: '/_app/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AppAdminRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/snackbar/$id': {
      id: '/_app/snackbar/$id'
      path: '/snackbar/$id'
      fullPath: '/snackbar/$id'
      preLoaderRoute: typeof AppSnackbarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/owner/reviews': {
      id: '/_app/owner/reviews'
      path: '/reviews'
      fullPath: '/owner/reviews'
      preLoaderRoute: typeof AppOwnerReviewsRouteImport
      parentRoute: typeof AppOwnerRoute
    }
    '/_app/owner/profile': {
      id: '/_app/owner/profile'
      path: '/profile'
      fullPath: '/owner/profile'
      preLoaderRoute: typeof AppOwnerProfileRouteImport
      parentRoute: typeof AppOwnerRoute
    }
    '/_app/owner/orders': {
      id: '/_app/owner/orders'
      path: '/orders'
      fullPath: '/owner/orders'
      preLoaderRoute: typeof AppOwnerOrdersRouteImport
      parentRoute: typeof AppOwnerRoute
    }
    '/_app/owner/menu': {
      id: '/_app/owner/menu'
      path: '/menu'
      fullPath: '/owner/menu'
      preLoaderRoute: typeof AppOwnerMenuRouteImport
      parentRoute: typeof AppOwnerRoute
    }
  }
}

interface AppOwnerRouteChildren {
  AppOwnerMenuRoute: typeof AppOwnerMenuRoute
  AppOwnerOrdersRoute: typeof AppOwnerOrdersRoute
  AppOwnerProfileRoute: typeof AppOwnerProfileRoute
  AppOwnerReviewsRoute: typeof AppOwnerReviewsRoute
}

const AppOwnerRouteChildren: AppOwnerRouteChildren = {
  AppOwnerMenuRoute: AppOwnerMenuRoute,
  AppOwnerOrdersRoute: AppOwnerOrdersRoute,
  AppOwnerProfileRoute: AppOwnerProfileRoute,
  AppOwnerReviewsRoute: AppOwnerReviewsRoute,
}

const AppOwnerRouteWithChildren = AppOwnerRoute._addFileChildren(
  AppOwnerRouteChildren,
)

interface AppRouteChildren {
  AppAdminRoute: typeof AppAdminRoute
  AppHomeRoute: typeof AppHomeRoute
  AppMapRoute: typeof AppMapRoute
  AppOwnerRoute: typeof AppOwnerRouteWithChildren
  AppProfileRoute: typeof AppProfileRoute
  AppSearchRoute: typeof AppSearchRoute
  AppSnackbarIdRoute: typeof AppSnackbarIdRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAdminRoute: AppAdminRoute,
  AppHomeRoute: AppHomeRoute,
  AppMapRoute: AppMapRoute,
  AppOwnerRoute: AppOwnerRouteWithChildren,
  AppProfileRoute: AppProfileRoute,
  AppSearchRoute: AppSearchRoute,
  AppSnackbarIdRoute: AppSnackbarIdRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
